spring.application.name=sslMle

server.port=8080

# Feign Client Configuration
feign.client.echo.url=http://localhost:${server.port}

# Feign Logging (requires logger level DEBUG for feign clients)
logging.level.com.wiggleji.sslmle.client=DEBUG
